export const SCENE_KEYS = Object.freeze({
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  WORLD_SCENE: 'WORLD_SCENE',
  BATTLE_SCENE: 'BATTLE_SCENE',

  COOKING_POT_SCENE: 'COOKING_POT_SCENE',
  INVENTORY_SCENE: 'INVENTORY_SCENE',
  COOKING_POST_SCENE: 'COOKING_POST_SCENE',
});
